# Generated by Django 2.2 on 2019-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190429_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='type',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main.Ingredient'),
        ),
    ]
