# Generated by Django 2.2 on 2019-04-29 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ccal', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Diet'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Difficulty'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Type'),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='recipes',
            field=models.ManyToManyField(related_name='cuis_of_rec', to='main.Recipe'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='recipes',
            field=models.ManyToManyField(related_name='diet_of_rec', to='main.Recipe'),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='recipes',
            field=models.ManyToManyField(related_name='diff_of_rec', to='main.Recipe'),
        ),
        migrations.AlterField(
            model_name='type',
            name='recipes',
            field=models.ManyToManyField(related_name='type_of_rec', to='main.Recipe'),
        ),
        migrations.DeleteModel(
            name='Ingridient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.ManyToManyField(related_name='ingr_of_rec', to='main.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='rec_of_ingr', to='main.Ingredient'),
        ),
    ]
