# Generated by Django 2.2 on 2019-05-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190502_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_by',
        ),
    ]
