# Generated by Django 2.2 on 2019-05-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_recipe_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='main.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
