# Generated by Django 2.2 on 2019-05-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190508_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'Difficulty', 'verbose_name_plural': 'Difficulties'},
        ),
    ]
