# Generated by Django 2.2 on 2019-05-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_recipe_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='likes',
        ),
    ]
